config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :cvbuilders
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #admin namespace
  namespace :admin do
    resources :skills
    resources :awards
    resources :achievements
    resources :resumes
    resources :templates
    resources :hobbies
    resources :educations
    resources :experiences
    resources :users
    resources :schools
    resources :companies
    resources :domains
    resources :countries
    resources :languages
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/award.rb
class Admin::Award < ApplicationRecord

  self.table_name = "awards"
  belongs_to :user
end

app/models/admin/company.rb
class Admin::Company < ApplicationRecord

  belongs_to :domain, :class_name => 'Admin::Domain'
  self.table_name = "companies"
end

app/models/admin/country.rb
class Admin::Country < ApplicationRecord

  self.table_name = "countries"
end

app/models/admin/domain.rb
class Admin::Domain < ApplicationRecord

  self.table_name = "domains"
  belongs_to :domain, optional: true , :class_name => 'Admin::Domain', :foreign_key => "parent_id"
end

app/models/admin/education.rb
class Admin::Education < ApplicationRecord
  self.table_name = "educations"
  belongs_to :school, :class_name => 'Admin::School'
end

app/models/admin/experience.rb
class Admin::Experience < ApplicationRecord
  self.table_name = "experiences"
  belongs_to :company, :class_name => 'Admin::Company'
  belongs_to :user, :class_name => 'Admin::User'
end

app/models/admin/hobby.rb
class Admin::Hobby < ApplicationRecord
  self.table_name = "hobbies"
  has_and_belongs_to_many :users, :class_name => 'Admin::User'
end

app/models/admin/language.rb
class Admin::Language < ApplicationRecord

  self.table_name = "languages"
  has_and_belongs_to_many :resumes, :class_name => 'Admin::Resume'
end

app/models/admin/resume.rb
class Admin::Resume < ApplicationRecord
  self.table_name = "resumes"
  before_validation :set_code
  belongs_to :user
  has_and_belongs_to_many :languages, :class_name => 'Admin::Language'
  has_and_belongs_to_many :templates, :class_name => 'Admin::Template'

  def set_code
    self.code = (self.code == nil?) ? SecureRandom.uuid : self.code
  end

end

app/models/admin/school.rb
class Admin::School < ApplicationRecord
  self.table_name = "schools"
  belongs_to :country, :class_name => 'Admin::Country'
end

app/models/admin/skill.rb
class Admin::Skill < ApplicationRecord

  self.table_name = "skills"
  has_and_belongs_to_many :users, :class_name => 'Admin::User'
end

app/models/admin/template.rb
class Admin::Template < ApplicationRecord
  self.table_name= "templates"
  belongs_to :domain
  has_and_belongs_to_many :resumes, :class_name => 'Admin::Resume'
end

app/models/admin/user.rb
class Admin::User < ApplicationRecord

  self.table_name = "users"
  belongs_to :country
  has_many :resumes, :class_name => 'Admin::Resume'
  has_secure_password
  has_and_belongs_to_many :hobbies, :class_name => 'Admin::Hobby'
  has_and_belongs_to_many :skills, :class_name => 'Admin::Skill'
  before_create :set_user_slug

  def set_user_slug
    loop do
      self.user_slug = SecureRandom.hex(5)
      break unless self.class.exists?(:user_slug => user_slug)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/hobbies_controller.rb
class Admin::HobbiesController < ApplicationController
  before_action :set_admin_hobby, only: [:show, :edit, :update, :destroy]

  # GET /admin/hobbies
  # GET /admin/hobbies.json
  def index
    @admin_hobbies = Admin::Hobby.all
    respond_to do |format|
      format.html
      format.json {render json: Admin::HobbyDatatable.new(params)}
    end
  end

  # GET /admin/hobbies/1
  # GET /admin/hobbies/1.json
  def show
  end

  # GET /admin/hobbies/new
  def new
    @admin_hobby = Admin::Hobby.new
  end

  # GET /admin/hobbies/1/edit
  def edit
  end

  # POST /admin/hobbies
  # POST /admin/hobbies.json
  def create
    @admin_hobby = Admin::Hobby.new(admin_hobby_params)

    respond_to do |format|
      if @admin_hobby.save
        format.html { redirect_to @admin_hobby, notice: 'Hobby was successfully created.' }
        format.json { render :show, status: :created, location: @admin_hobby }
      else
        format.html { render :new }
        format.json { render json: @admin_hobby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/hobbies/1
  # PATCH/PUT /admin/hobbies/1.json
  def update
    respond_to do |format|
      if @admin_hobby.update(admin_hobby_params)
        format.html { redirect_to @admin_hobby, notice: 'Hobby was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_hobby }
      else
        format.html { render :edit }
        format.json { render json: @admin_hobby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/hobbies/1
  # DELETE /admin/hobbies/1.json
  def destroy
    @admin_hobby.destroy
    respond_to do |format|
      format.html { redirect_to admin_hobbies_url, notice: 'Hobby was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_hobby
      @admin_hobby = Admin::Hobby.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_hobby_params
      params.require(:admin_hobby).permit(:name, :icon, :status, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  #split_code will split a string returning strings and numbers in two different vars
  def split_code(string)
    chars = numbers = ''
    code = string.split('')
    if code.length > 0
      code.each do |char|
        if char =~ /\A[-+]?[0-9]+\z/
          numbers += char
        else
          chars += char
        end
      end
    end
    [chars, numbers]
  end

  def index
    render layout: 'layouts/front-end'
  end

  def home
    #@user = Admin::User.order("RAND()").includes(:resumes).first
    @user = Admin::User.find(1)
    session[:user_id] = @user.id
    render layout: 'layouts/front-end'
  end

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController

  def index
    @resume = Admin::Resume.where(code: params['code']).includes(:user, :templates).first
    respond_to do |format|
      format.html
      format.pdf do
        @pdf = render_to_string :pdf => "#{@resume.name}.pdf", :template => 'resumes/index.html.erb', :encoding => "UTF-8"
        send_data(@pdf, :filename => "#{@resume.name}.pdf", :type=>"application/pdf")
      #format.pdf do render :pdf => "file.pdf", :template => 'resumes/index.html.erb'
      end
    end
  end

  def builder
    @resume = Admin::Resume.first
    render layout: 'layouts/front-end'
  end

  def get_html
    ActionController::Base.new.render_to_string(template: 'resumes/index.html.erb',
                                                orientation: 'landscape',
                                                page_size: 'Letter',
                                                background: true
    )
  end
end

app/helpers/admin/hobbies_helper.rb
module Admin::HobbiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/admin/hobbies/_form.html.erb
<%= form_with(model: admin_hobby, local: true) do |form| %>
  <% if admin_hobby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_hobby.errors.count, "error") %> prohibited this admin_hobby from being saved:</h2>

      <ul>
      <% admin_hobby.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :icon %>
    <%= form.text_field :icon %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/hobbies/edit.html.erb
<h1>Editing Admin Hobby</h1>

<%= render 'form', admin_hobby: @admin_hobby %>

<%= link_to 'Show', @admin_hobby %> |
<%= link_to 'Back', admin_hobbies_path %>

app/views/admin/hobbies/index.html.erb
<%= content_for :dashboard_content do %>
  <div class="card">
    <div class="card-header card-header-primary">
      <p id="notice"><%= notice %></p>
      <h3>Admin Hobbies</h3>
    </div>
    <div class="card-body">
      <table id="hobbies-dt" class="table table-bordered table-striped" width="100%" data-source="<%= admin_hobbies_path %>">
        <%= link_to 'Add hobby', new_admin_hobby_path, class: 'btn btn-primary' %>
        <thead>
          <tr>
            <th>Name</th>
            <th>User</th>
            <th>Status</th>
            <th></th>
          </tr>
        </thead>
        <tbody></tbody>
        <!--<tbody>
          <%# @admin_hobbies.each do |admin_hobby| %>
            <tr>
              <td><%#= admin_hobby.name %></td>
              <td><%#= admin_hobby.icon %></td>
              <td><%#= admin_hobby.status %></td>
              <td><%#= admin_hobby.user %></td>
              <td><%#= link_to 'Show', admin_hobby %></td>
              <td><%#= link_to 'Edit', edit_admin_hobby_path(admin_hobby) %></td>
              <td><%#= link_to 'Destroy', admin_hobby, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <%# end %>
        </tbody>-->
      </table>
<% end %>
<%= render :template => 'layouts/material_dashboard' %>

app/views/admin/hobbies/new.html.erb
<h1>New Admin Hobby</h1>

<%= render 'form', admin_hobby: @admin_hobby %>

<%= link_to 'Back', admin_hobbies_path %>

app/views/admin/hobbies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_hobby.name %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @admin_hobby.icon %>
</p>

<p>
  <strong>Status:</strong>
  <%= @admin_hobby.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @admin_hobby.user %>
</p>

<%= link_to 'Edit', edit_admin_hobby_path(@admin_hobby) %> |
<%= link_to 'Back', admin_hobbies_path %>