config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :cvbuilders
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #admin namespace
  namespace :admin do
    resources :skills
    resources :awards
    resources :achievements
    resources :resumes
    resources :templates
    resources :hobbies
    resources :educations
    resources :experiences
    resources :users
    resources :schools
    resources :companies
    resources :domains
    resources :countries
    resources :languages
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/achievement.rb
class Admin::Achievement < ApplicationRecord

  self.table_name = "achievements"
  belongs_to :user
end

app/models/admin/award.rb
class Admin::Award < ApplicationRecord

  self.table_name = "awards"
  belongs_to :user
end

app/models/admin/company.rb
class Admin::Company < ApplicationRecord

  belongs_to :domain, :class_name => 'Admin::Domain'
  self.table_name = "companies"
end

app/models/admin/country.rb
class Admin::Country < ApplicationRecord

  self.table_name = "countries"
end

app/models/admin/domain.rb
class Admin::Domain < ApplicationRecord

  self.table_name = "domains"
  belongs_to :domain, optional: true , :class_name => 'Admin::Domain', :foreign_key => "parent_id"
end

app/models/admin/education.rb
class Admin::Education < ApplicationRecord
  self.table_name = "educations"
  belongs_to :school, :class_name => 'Admin::School'
end

app/models/admin/hobby.rb
class Admin::Hobby < ApplicationRecord
  self.table_name = "hobbies"
  has_and_belongs_to_many :users, :class_name => 'Admin::User'
end

app/models/admin/language.rb
class Admin::Language < ApplicationRecord

  self.table_name = "languages"
  has_and_belongs_to_many :resumes, :class_name => 'Admin::Resume'
end

app/models/admin/resume.rb
class Admin::Resume < ApplicationRecord
  self.table_name = "resumes"
  before_validation :set_code
  belongs_to :user
  has_and_belongs_to_many :languages, :class_name => 'Admin::Language'
  has_and_belongs_to_many :templates, :class_name => 'Admin::Template'

  def set_code
    self.code = (self.code == nil?) ? SecureRandom.uuid : self.code
  end

end

app/models/admin/school.rb
class Admin::School < ApplicationRecord
  self.table_name = "schools"
  belongs_to :country, :class_name => 'Admin::Country'
end

app/models/admin/skill.rb
class Admin::Skill < ApplicationRecord

  self.table_name = "skills"
  has_and_belongs_to_many :users, :class_name => 'Admin::User'
end

app/models/admin/template.rb
class Admin::Template < ApplicationRecord
  self.table_name= "templates"
  belongs_to :domain
  has_and_belongs_to_many :resumes, :class_name => 'Admin::Resume'
end

app/models/admin/user.rb
class Admin::User < ApplicationRecord

  self.table_name = "users"
  belongs_to :country
  has_many :resumes, :class_name => 'Admin::Resume'
  has_secure_password
  has_and_belongs_to_many :hobbies, :class_name => 'Admin::Hobby'
  has_and_belongs_to_many :skills, :class_name => 'Admin::Skill'
  before_create :set_user_slug

  def set_user_slug
    loop do
      self.user_slug = SecureRandom.hex(5)
      break unless self.class.exists?(:user_slug => user_slug)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/achievements_controller.rb
class Admin::AchievementsController < ApplicationController
  before_action :set_admin_achievement, only: [:show, :edit, :update, :destroy]

  # GET /admin/achievements
  # GET /admin/achievements.json
  def index
    @admin_achievements = Admin::Achievement.all
    respond_to do |format|
      format.html
      format.json {render :json => Admin::AchievementDatatable.new(params)}
    end
  end

  # GET /admin/achievements/1
  # GET /admin/achievements/1.json
  def show
  end

  # GET /admin/achievements/new
  def new
    @admin_achievement = Admin::Achievement.new
  end

  # GET /admin/achievements/1/edit
  def edit
  end

  # POST /admin/achievements
  # POST /admin/achievements.json
  def create
    @admin_achievement = Admin::Achievement.new(admin_achievement_params)

    respond_to do |format|
      if @admin_achievement.save
        format.html { redirect_to @admin_achievement, success: 'Achievement was successfully created.' }
        format.json { render :show, status: :created, location: @admin_achievement }
      else
        format.html { render :new }
        format.json { render json: @admin_achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/achievements/1
  # PATCH/PUT /admin/achievements/1.json
  def update
    respond_to do |format|
      if @admin_achievement.update(admin_achievement_params)
        format.html { redirect_to @admin_achievement, success: 'Achievement was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_achievement }
      else
        format.html { render :edit }
        format.json { render json: @admin_achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/achievements/1
  # DELETE /admin/achievements/1.json
  def destroy
    @admin_achievement.destroy
    respond_to do |format|
      format.html { redirect_to admin_achievements_url, success: 'Achievement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_achievement
      @admin_achievement = Admin::Achievement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_achievement_params
      params.require(:admin_achievement).permit(:user_id, :title, :description, :status)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  #split_code will split a string returning strings and numbers in two different vars
  def split_code(string)
    chars = numbers = ''
    code = string.split('')
    if code.length > 0
      code.each do |char|
        if char =~ /\A[-+]?[0-9]+\z/
          numbers += char
        else
          chars += char
        end
      end
    end
    [chars, numbers]
  end

  def index
    render layout: 'layouts/front-end'
  end

  def home
    #@user = Admin::User.order("RAND()").includes(:resumes).first
    @user = Admin::User.find(1)
    session[:user_id] = @user.id
    render layout: 'layouts/front-end'
  end

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController

  def index
    @resume = Admin::Resume.where(code: params['code']).includes(:user, :templates).first
    respond_to do |format|
      format.html
      format.pdf do
        @pdf = render_to_string :pdf => "#{@resume.name}.pdf", :template => 'resumes/index.html.erb', :encoding => "UTF-8"
        send_data(@pdf, :filename => "#{@resume.name}.pdf", :type=>"application/pdf")
      #format.pdf do render :pdf => "file.pdf", :template => 'resumes/index.html.erb'
      end
    end
  end

  def builder
    @resume = Admin::Resume.first
    render layout: 'layouts/front-end'
  end

  def get_html
    ActionController::Base.new.render_to_string(template: 'resumes/index.html.erb',
                                                orientation: 'landscape',
                                                page_size: 'Letter',
                                                background: true
    )
  end
end

app/helpers/admin/achievements_helper.rb
module Admin::AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/admin/achievements/_form.html.erb
<%= form_with(model: admin_achievement, local: true) do |form| %>
  <% if admin_achievement.errors.any? %>
    <div id="error_explanation">
      <strong><%= pluralize(admin_achievement.errors.count, "error") %> prohibited this admin_achievement from being saved:</strong>

      <ul class="alert alert-danger">
      <% admin_achievement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="field col-md-6">
      <div class="form-group bmd-form-group">
        <%= form.label :user_id, class: 'bmd-label-floating' %>
        <%= form.select :user_id, Admin::User.pluck([:name, :id]), {include_blank: true},{ :class => 'form-control'} %>
      </div>
    </div>
    <div class="field col-md-6">
      <div class="form-group bmd-form-group">
        <label class="bmd-label-floating">Title</label>
        <%= form.text_field :title, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="field col-md-6">
      <div class="form-group bmd-form-group">
        <%= form.label :description, class: 'bmd-label-floating'%>
        <%= form.text_area :description, class: 'form-control' %>
      </div>
    </div>
    <div class="field col-md-6">
      <div class="form-group bmd-form-group">
        <%= form.label :status, class: 'bmd-label-floating' %>
        <%= form.number_field :status, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "Save" ,class: "btn btn-default" %>
  </div>
<% end %>

app/views/admin/achievements/edit.html.erb
<%= content_for :dashboard_content do %>
  <div class="card">
    <div class="card-header card-header-primary"><h3>Editing Admin Achievement</h3></div>
    <div class="card-body">
      <%= render 'form', admin_achievement: @admin_achievement %>
    </div>
  </div>
  <%= link_to 'Show', @admin_achievement %> |
  <%= link_to 'Back', admin_achievements_path %>
<% end %>
<%= render template: "layouts/material_dashboard" %>

app/views/admin/achievements/index.html.erb
<% content_for :dashboard_content do %>
  <div class="card">
    <div class="card-header card-header-primary">
      <p id="notice"><%= notice %></p>
      <h3>Achievements</h3>
    </div>
    <div class="card-body">
      <div id="notice">
        <% flash.each do |class_name, message| %>
          <div class="alert alert-<%= class_name %>"><%= message %></div>
        <% end %>
      </div>
      <%= link_to 'Add achievement', new_admin_achievement_path, class: "btn btn-primary" %>
      <table id="achievements-dt" data-source="<%= admin_achievements_path %>" width="100%" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Title</th>
            <th>User</th>
            <th>Status</th>
            <th></th>
          </tr>
        </thead>
        <tbody></tbody>
      </table>
    </div>
  </div>
<% end %>
<%= render template: 'layouts/material_dashboard' %>

app/views/admin/achievements/new.html.erb
<%= content_for :dashboard_content do %>
  <div class="card">
    <div class="card-header card-header-primary"><h3>Add achievement</h3></div>
    <div class="card-body">
      <%= render 'form', admin_achievement: @admin_achievement %>
      <%= link_to 'Back', admin_achievements_path, class: "btn btn-default" %>
    </div>
  </div>
<% end %>
<%= render template: 'layouts/material_dashboard' %>

app/views/admin/achievements/show.html.erb
<%= content_for :dashboard_content do %>
  <div class="card card-profile">
    <div class="card-avatar"></div>
    <div class="card-body">
      <div id="notice">
        <% flash.each do |class_name, message| %>
          <div class="alert alert-<%= class_name %>"><%= message %></div>
        <% end %>
      </div>
      <div>
        <h3><%= @admin_achievement.title %></h3>
      </div>
      <div>
        <strong><%= @admin_achievement.user.name %> <br> <%= link_to "User's details", admin_achievement_path(@admin_achievement.user.id) %></strong>
      </div>
      <p>
        <!--<strong>Description:</strong>-->
        <%= @admin_achievement.description %>
      </p>
      <!--<p>
        <strong>Status:</strong>
        < %= @admin_achievement.status %>
      </p>-->
      <a href="<%= edit_admin_achievement_path(@admin_achievement) %>" class="btn btn-primary"><i class="material-icons">create</i> Edit </a> |
      <a href="<%= admin_achievements_path %>" class="btn btn-default"><i class="material-icons">navigate_before</i> Back</a>
    </div>
  </div>
<% end %>
<%= render template: 'layouts/material_dashboard' %>